spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ping?useUnicode=true&useSSL=true
    username: root
    password: 123123
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8881